### ISSUE TITLE
Unable to execute test case in Firefox with browser version configured in the Test set run manager.

### ISSUE THREAD

**Issue by Shantha93** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#121]
[ ] bug report   

**Current behavior**
Unable to execute any test case when the test case is configured with a browser version in the test set run manager panel in the test execution window.

**Expected behavior**
Test case configured with a browser version for Firefox, in the execution window should run producing a console log.

**Comment by kumarkrish85** [comment]
The same issue occurs in selenium (3.5.3) as well. Please refer the below code

`import org.openqa.selenium.Platform;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.DesiredCapabilities;

public class Main {

	public static void main(String[] args) {
		DesiredCapabilities capa = new DesiredCapabilities();
		capa.setCapability("acceptInsecureCerts", true);
		capa.setVersion("65.0");
		capa.setPlatform(Platform.ANY);
		System.setProperty("webdriver.gecko.driver",
				"C:\\Users\\589103\\Downloads\\cognizant-intelligent-test-scripter-1.3-setup\\cognizant-intelligent-test-scripter-1.3\\lib\\Drivers\\geckodriver.exe");
		WebDriver driver = new FirefoxDriver(withFirefoxProfile(capa));
		driver.get("https://bing.com");
		driver.close();
	}

	private static FirefoxOptions withFirefoxProfile(DesiredCapabilities caps) {
		FirefoxOptions fOptions = new FirefoxOptions();
		// fOptions.merge(caps);
		fOptions.addCapabilities(caps);
		FirefoxProfile fProfile;
		fProfile = new FirefoxProfile();

		// Patch provided in addGeckoDriverAddon
		// if (SystemDefaults.getClassesFromJar.get() && SystemDefaults.debugMode.get())
		// {
		// if (FilePath.getFireFoxAddOnPath().exists()) {
		// fProfile.addExtension(FilePath.getFireFoxAddOnPath());
		// }
		// }
		// fProfile = addFFProfile(fProfile);
		// caps.setCapability(FirefoxDriver.PROFILE, fProfile);
		String binPath = System.getProperty("firefox.bin.path");
		if (binPath != null && !binPath.isEmpty()) {
			fOptions.setBinary(binPath);
		}
		return fOptions;
	}
}`

FYI the issue is not reproducible in latest selenium version
